package com.example.musicplayer.feature_musicPlayer.core.constants

object Constants {
    const val ACTION_SERVICE_START = "ACTION_SERVICE_START"
    const val ACTION_SERVICE_STOP = "ACTION_SERVICE_STOP"
    const val ACTION_SERVICE_NEXT = "ACTION_SERVICE_NEXT"
    const val ACTION_SERVICE_PREVIOUS = "ACTION_SERVICE_PREVIOUS"

    const val MUSIC_PLAYER_STATE = "MUSIC_PLAYER_STATE"

    const val NOTIFICATION_CHANNEL_ID = "MUSIC_PLAYER_NOTIFICATION_ID"
    const val NOTIFICATION_CHANNEL_NAME = "MUSIC_PLAYER_NOTIFICATION"
    const val NOTIFICATION_ID = 20

    const val CLICK_REQUEST_CODE = 100
    const val START_REQUEST_CODE = 101
    const val STOP_REQUEST_CODE = 102
    const val NEXT_REQUEST_CODE = 103
    const val PREVIOUS_REQUEST_CODE = 104
}